---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: admin
  userKey: AQB+M3le2Q6EOxAAVf9rxe6cl1apkDgdqtzjFA==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQB+M3le2Q6EOxAAVf9rxe6cl1apkDgdqtzjFA==
