---
apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: ceph-csi
stringData:
  # Required for statically provisioned volumes
  userID: admin
  userKey: AQAkimpeK1SfHhAA61MzxaEtz0QvEAjowOK4Fg==

  # Required for dynamically provisioned volumes
  adminID: admin
  adminKey: AQAkimpeK1SfHhAA61MzxaEtz0QvEAjowOK4Fg==
